project:
  type: website
  output-dir: docs

link-external-icon: true
anchor-sections: false

format:
  html:
    theme: custom.scss
    toc: true
    toc-depth: 4
    df-print: paged
    highlight-style: monochrome
    code-overflow: wrap
    code-block-bg: $dark-alt
    code-block-border-left: $primary
    linkcolor: $primary-light
